<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Day2_Testsuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>afbd2346-d426-4e84-92de-ed5a367d43f5</testSuiteGuid>
   <testCaseLink>
      <guid>27b08cf2-c0db-4bf3-ae21-1c1d55f38714</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day2/data_TC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b332fcbb-8aca-41e8-af67-c02c2cada682</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/datasheet</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b332fcbb-8aca-41e8-af67-c02c2cada682</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserName</value>
         <variableId>1798ffa9-a06b-4c0f-a83f-79d23f8b92f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b332fcbb-8aca-41e8-af67-c02c2cada682</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PassWord</value>
         <variableId>f31565bd-139a-48f9-a863-379356783561</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
